feat: split nightly tests

diff --git a/.github/workflows/nightly.yml b/.github/workflows/nightly.yml
--- a/.github/workflows/nightly.yml
+++ b/.github/workflows/nightly.yml
@@ -14,8 +14,11 @@ on:
         default: '-m "not devRun"'
 
 jobs:
-  nightly:
+  nightly-test:
     runs-on: ubuntu-latest
+    strategy:
+      matrix:
+        group: [1, 2]
     steps:
       - uses: actions/checkout@v4
       - name: Set up Python
@@ -38,31 +41,53 @@ jobs:
         run: poetry install --no-interaction --no-root
       - name: Install Playwright Browsers
         run: npx playwright install --with-deps
-      - name: Run custom pytest command
-        if: github.event_name == 'workflow_dispatch'
+      - name: Run tests
         run: |
+          mkdir -p exit-code allure-results
           source .venv/bin/activate
-          xvfb-run pytest ${{ github.event.inputs.pytest_command }} --base-url ${{ vars.BASE_URL }}
-      - name: Run default pytest command
-        if: github.event_name != 'workflow_dispatch'
-        run: |
-          source .venv/bin/activate
-          xvfb-run pytest -m "not devRun" --base-url ${{ vars.BASE_URL }}
-      - name: Store Playwright Traces and Videos From Failed Tests
-        if: failure()
+          exit_code=0
+          {
+            xvfb-run pytest ${{ github.event.inputs.pytest_command || '-m "not devRun"' }} \
+              --base-url ${{ vars.BASE_URL }} \
+              --splits 2 \
+              --group ${{ matrix.group }}
+          } || {
+            exit_code=$?
+          }
+          echo $exit_code > exit-code/shard_${{ matrix.group }}.txt
+      - name: Upload test results and artifacts
         uses: actions/upload-artifact@v4.3.3
-        id: artifact-upload-step
         with:
-          name: test-results
-          path: test-results/
+          name: test-results-${{ matrix.group }}
+          path: |
+            test-results/
+            allure-results
+            exit-code
           retention-days: 7
+
+  merge-reports:
+    needs: nightly-test
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - name: Download all test results
+        uses: actions/download-artifact@v4
+        with:
+          path: artifacts
+      - name: Merge Allure results
+        run: |
+          mkdir -p allure-results
+          for dir in artifacts/test-results-*/allure-results; do
+            cp -r $dir/* allure-results/
+          done
       - name: Link Playwright Traces And Videos To Allure Report
         working-directory: allure-results
-        if: failure()
-        run: echo ARTIFACT_URL=${{ steps.artifact-upload-step.outputs.artifact-url }} >> environment.properties
+        run: |
+          for dir in artifacts/test-results-*; do
+            echo "ARTIFACT_URL_$(basename $dir)=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> environment.properties
+          done
       - name: Link Git Information And Browser Version To Allure Report
         working-directory: allure-results
-        if: always()
         run: |
           {
            echo BUILD_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
@@ -88,3 +113,10 @@ jobs:
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_dir: allure-history
+      - name: Check test results
+        run: |
+          exit_codes=$(cat artifacts/test-results-*/exit-code/shard_*.txt)
+          if echo "$exit_codes" | grep -q -v '^0$'; then
+            echo "Some tests failed. Failing the job."
+            exit 1
+          fi
